project:
  type: website
  output-dir: docs

website:
  title: "Dynamic Social Mind Lab"
  navbar:
    logo: img/socialmind.png
    background: "#8a3028"
    right:
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme:
      light: journal
      dark: darkly
    css: css/navbar.css  # 引入自定义 CSS
editor: visual