project:
  type: website
  output-dir: docs

website:
  title: "MichaelZ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
  #light & dark mode switch
  #todo: modify to Chicago color through scss
    theme:
      light: [journal,css/Chicago.scss]
      dark: [journal,css/Chicago.scss,css/theme-dark.scss]
    #css:
      #- styles.css
    toc: true
    page-layout: full
editor: visual
