project:
  type: website
  output-dir: docs

website:
  title: "BaiX Lab"
  navbar:
    pinned: true
    right:
      - href: "#Welcome"
        text: Home
      - href: "#People"
        text: People
      - href: "#Research"
        text: Research 
      - href: "#Teaching"
        text: Teaching
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/BaiXLab
          - text: Lab Wiki
            href:  https://github.com/psymichaelzhu/BaiXLab/wiki/Random-forest
  sidebar: false

format:
  html:
    theme: simplex
editor: visual
