project:
  type: website
  output-dir: docs

website:
  title: "MichaelZ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
  #light & dark mode switch, with a Chicago-style navigation bar
    theme:
      light: darkly
      dark: [journal,css/theme-dark.scss,css/Chicago.scss]
    toc: true
    page-layout: full
editor: visual
