project:
  type: website
  output-dir: docs

website:
  title: "Dynamic Social Mind Lab"
  favicon: img/socialmind.png
  navbar:
    logo: img/socialmind.png
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research 
      - href: teaching.qmd
        text: Teaching
      - icon: github
        href: https://github.com/psymichaelzhu/MichaelZ
        aria-label: GitHub

format:
  html:
    theme: simplex
    css: 
      - css/custom.css
editor: visual