project:
  type: website
  output-dir: docs

website:
  title: "MichaelZ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
  #Light and dark mode switching, with a navigation bar in Chicago style.
    theme:
      light: [journal,css/Chicago.scss]
      dark: [journal,css/theme-dark.scss,css/Chicago.scss]
    toc: true
    page-layout: full
editor: visual
