project:
  type: website
  output-dir: docs

website:
  title: "Dynamic Social Mind Lab"
  favicon: img/socialmind.png
  navbar:
    logo: img/socialmind.png
    background: "#8a3028"
    right:
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications 
      - href: teaching.qmd
        text: Teaching
      - icon: github
        href: https://github.com/psymichaelzhu/MichaelZ
        aria-label: GitHub

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/navbar.css  # 引入自定义 CSS
editor: visual