project:
  type: website
  output-dir: docs

website:
  title: "BaiX Lab"
  navbar:
    pinned: true
    right:
      - href: "#Welcome"
        text: Home
      - href: "#People"
        text: People
      - href: "#Research"
        text: Research 
      - href: "#Teaching"
        text: Teaching
      - icon: github
        href: https://github.com/psymichaelzhu/MichaelZ
        aria-label: GitHub
  sidebar: false

format:
  html:
    theme: simplex
editor: visual
