project:
  type: website
  output-dir: docs

website:
  title: "Dynamic Social Mind Lab"
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: "#People"
        text: Research 
      - href: teaching.qmd
        text: Teaching
      - icon: github
        href: https://github.com/psymichaelzhu/MichaelZ
        aria-label: GitHub

format:
  html:
    theme: simplex
editor: visual
