project:
  type: website
  output-dir: docs

website:
  title: "MichaelZ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research 
      - href: teaching.qmd
        text: Teaching

format:
  html:
  #Light and dark mode switching, with a navigation bar in Chicago style.
    theme:
      light: [litera,css/Chicago.scss]
      dark: [litera,css/theme-dark.scss,css/Chicago.scss]
    #toc: true Skeleton
    page-layout: full
editor: visual
