---
about: 
  template: marquee
format:
  html:
    page-layout: full
    sidebar: false
    anchor-sections: false
---

## Welcome to the Dynamic Social Mind Lab

Our research studies the origin and evolution of mental representations of human groups. In particular, we take a dynamic perspective by asking two essentially interlinked questions: First, how do individual minds adaptively but selectively construct the social world? Second, how does the constructed social world mold individual minds?

Our research combines insights from social and cognitive psychology, computer science and machine learning, and public policy. We use multiple methodologies to pursue these questions, including cross-national surveys, large-scale online behavioral experiments, naturalistic text analyses, and computational cognitive models. Taking advantage of each discipline and method, our future research will study other aspects of dynamic social minds in both human and artificial social worlds.

*Dr.Bai will be reviewing materials for postdoc researcher, graduate student, and research assistant positions for the 2024-25 cycle, see details in this [doc](https://docs.google.com/document/d/1JW5j8dAAIbFh9dqOvugFkJ2GBon9CYhEoASSvwzZndk/edit?usp=sharing)*
